### ISSUE TITLE
nodegit@0.25.1 fails at install script.

### ISSUE THREAD

**Issue by nSedrickm** [Wisdom-Nji/deku_enterprise#3]
Dependency nodegit fails to install when npm install command is run

[2020-01-19T06_17_03_087Z-debug.log](https://github.com/Wisdom-Nji/deku_enterprise/files/4082980/2020-01-19T06_17_03_087Z-debug.log)

Error message:
nodegit@0.25.1 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
failed at the nodegit@0.25.1 install script.

OS : Debian GNU/Linux 10 (buster) x86_64
Nodejs : 13.7.0
NPM : 6.13.2

**Comment by sherlockwisdom** [comment]
please fix package and open pull request
